###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "first_name":"A",
    "last_name": "Yo",
    "email": "kiboole@gmail.com",
    "password": "123456"
}

### Get all user
GET http://localhost:3000/api/v1/users

### Create notification
POST http://localhost:3000/api/v1/notification/1
Content-Type: application/json

{
    "title": "Test 2",
    "message": "Haloo world"
}

###
GET http://localhost:3000/api/v1/notif/notification

###
POST https://challenge-7-be-js-rizki-robawas-projects.vercel.app/api/v1/users
Content-Type: application/json

{
    "first_name":"Rizki",
    "last_name": "Robawa",
    "email": "21082010208@student.upnjatim.ac.id",
    "password": "123456"
}