###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "first_name":"Pak",
    "last_name": "Woi",
    "email": "sonyexperiat3ultra@gmail.com",
    "password": "123456"
}

### Get all user
GET http://localhost:3000/api/v1/users

### Create notification
POST http://localhost:3000/api/v1/notification/1
Content-Type: application/json

{
    "title": "Test 2",
    "message": "Haloo world"
}

###
GET http://localhost:3000/api/v1/notif/notification